### ISSUE TITLE
[Bug] Stop donation / Cancel subscription not showing on Collective page. 

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#136]
![Screenshot 2024-01-30 at 4 18 34 PM](https://github.com/GoodDollar/GoodCollective/assets/149098646/c80ac4bd-f813-4ed0-8d6d-547f109b6bd8)
Subscription does not display on Collective screen.

I have a 5-day subscription streaming G$, and do not see the ability to cancel my subscription on the Collective screen. 

The out-standing subscription may be the cause of the error in[ ticket 135](https://github.com/GoodDollar/GoodCollective/issues/135)

**Comment by decentralauren** [comment]
OK the option DID appear, but many minutes after the donation was made. @krisbitney should we expect this kind of lag? If so we should adjust the language in the post-donation modal to say "may take a while to show up" etc. cc @patpedrosa

**Comment by krisbitney** [comment]
> OK the option DID appear, but many minutes after the donation was made. @krisbitney should we expect this kind of lag? If so we should adjust the language in the post-donation modal to say "may take a while to show up" etc. cc @patpedrosa

I added a performance optimization in this PR: https://github.com/GoodDollar/GoodCollective/pull/137

The delay depends on multiple factors. 
- The transaction needs to finalize
- The Subgraph needs to update with the new data from the smart contract
- The app needs to see the updated Subgraph data

I made it so the app checks more often if there is any new data in the Subgraph for this specific thing.

**Comment by vldkhh** [comment]
verified

**Comment by L03TJ3** [comment]
@vldkhh this was not merged yet, so needs re-qa'd

**Comment by krisbitney** [comment]
This is fixed in https://github.com/GoodDollar/GoodCollective/pull/137

**Comment by vldkhh** [comment]
@decentralauren @L03TJ3 see no issues with that 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1VlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0b69440739b534904d33ebf127f5efc42c14b1b/0A93532D-8FAA-43E0-97D9-2F92D7E9EF08.MP4)

**Comment by decentralauren** [comment]
Works as expected with G$ stream

I am unable to test with other currencies as I receive the "UNPREDICTABLE_GAS_LIMIT" error when donating. 
@vldkhh were you able to test with non-G$?

**Comment by vldkhh** [comment]
@krisbitney @decentralauren I'm not able to stop my donation after using Celo 
![image](https://github.com/GoodDollar/GoodCollective/assets/107620432/4dee1d63-c43b-4f66-b6f3-0a7e531e49ef)

**Comment by krisbitney** [comment]
@vldkhh Whether you use Celo or not is unrelated to stopping the donation, but I think I may have found the issue. I think this PR should fix it: https://github.com/GoodDollar/GoodCollective/pull/178

**Comment by vldkhh** [comment]
@krisbitney checked on the deployment above, and it is still reproducing + fetchfullnames info logs keep increasing. could you double check it?

https://github.com/GoodDollar/GoodCollective/assets/107620432/193aa396-5b69-4ec8-9c56-a926a883393c

**Comment by krisbitney** [comment]
> @krisbitney checked on the deployment above, and it is still reproducing + fetchfullnames info logs keep increasing. could you double check it?
> 
>  1BACF17F-5838-4C87-8893-8FC6B4E207BB.MP4

The log isn't something I added. I'll leave that to your team.

If the stop donation error is still reproducing, it's a smart contract issue. The front end only supplies the inputs to the smart contract calls. The `deleteFlow` method is very simple.

```ts
const tx = await sdk.deleteFlow(signer, collective, '0');
```

I double checked and confirmed the correct collective address is being passed in. The other parameters are a constant and the signer.

@sirpy

**Comment by L03TJ3** [comment]
Ye that log is mine. I am trying to figure out what makes the fetching of transactions end up in an endless cycle @vldkhh 

@krisbitney not asking you to fix it but do you have any idea what can cause this? It seems to be the fetch query for donations, but I haven't figured out yet why?

**Comment by krisbitney** [comment]
> Ye that log is mine. I am trying to figure out what makes the fetching of transactions end up in an endless cycle @vldkhh
> 
> @krisbitney not asking you to fix it but do you have any idea what can cause this? It seems to be the fetch query for donations, but I haven't figured out yet why?

No, I didn't realize it was happening. I'll take a look.

**Comment by krisbitney** [comment]
@L03TJ3 I don't think `useFetchFullNames` is being called endlessly due to repeated fetching transactions. The useMemo hook that depends on the `donations` and `claims` arrays isn't repeatedly called, suggesting the same `donations` and `claims` arrays are used.

This TODO comment is likely related to the poll interval having been 1 second:
```ts
  //todo-fix: donations is called endlessly
  const donations: Transaction[] | undefined = useRecentDonations(collective, maxN, donationsPollInterval);
  ```

**Comment by L03TJ3** [comment]
@krisbitney 

place a log in supporttranasctionlistitem
and watch console.

that is what I traced back to useRecentTransactions.

**Comment by krisbitney** [comment]
> @krisbitney
> 
> place a log in supporttranasctionlistitem and watch console.
> 
> that is what I traced back to useRecentTransactions.

I see it. I think the issue might be the flowing balance. It should probably be isolated in its own component, kind of like the `FlowingBalanceRowItem` component.

**Comment by L03TJ3** [comment]
@krisbitney isn't this likely to happen to any component where we try and merge the transactions?

**Comment by krisbitney** [comment]
> @krisbitney isn't this likely to happen to any component where we try and merge the transactions?

I think it should only affect the `SupoprtTransactionListItem` and its children

**Comment by decentralauren** [comment]
@vldkhh @L03TJ3 can you confirm the fix / retest so we can close?

**Comment by decentralauren** [comment]
@vldkhh please retest :)

**Comment by vldkhh** [comment]
@decentralauren works for me 
![Snag_2fc5e90e](https://github.com/GoodDollar/GoodCollective/assets/107620432/14273539-adac-420e-b44a-3144f429baef)
